
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PlayerStates : Luban.BeanBase
{
    public PlayerStates(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["info"].IsString) { throw new SerializationException(); }  Info = _buf["info"]; }
        { if(!_buf["anm_name"].IsString) { throw new SerializationException(); }  AnmName = _buf["anm_name"]; }
        { if(!_buf["on_anm_end"].IsNumber) { throw new SerializationException(); }  OnAnmEnd = _buf["on_anm_end"]; }
        { var __json0 = _buf["on_move"]; if(!__json0.IsArray) { throw new SerializationException(); } OnMove = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  OnMove.Add(__v0); }   }
    }

    public static PlayerStates DeserializePlayerStates(JSONNode _buf)
    {
        return new PlayerStates(_buf);
    }

    /// <summary>
    /// 状态ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Info;
    /// <summary>
    /// 动画名称
    /// </summary>
    public readonly string AnmName;
    /// <summary>
    /// 当动作结束
    /// </summary>
    public readonly int OnAnmEnd;
    /// <summary>
    /// 当进行移动<br/>前摇/后摇/下一个状态
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnMove;
   
    public const int __ID__ = -88392605;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "info:" + Info + ","
        + "anmName:" + AnmName + ","
        + "onAnmEnd:" + OnAnmEnd + ","
        + "onMove:" + Luban.StringUtil.CollectionToString(OnMove) + ","
        + "}";
    }
}
}

