
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbPlayerStateData TbPlayerStateData {get; }
    public TbUnitAttData TbUnitAttData {get; }
    public TbUnitData TbUnitData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbPlayerStateData = new TbPlayerStateData(loader("tbplayerstatedata"));
        TbUnitAttData = new TbUnitAttData(loader("tbunitattdata"));
        TbUnitData = new TbUnitData(loader("tbunitdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbPlayerStateData.ResolveRef(this);
        TbUnitAttData.ResolveRef(this);
        TbUnitData.ResolveRef(this);
    }
}

}
