
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPlayerStates
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerStates> _dataMap;
    private readonly System.Collections.Generic.List<PlayerStates> _dataList;
    
    public TbPlayerStates(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerStates>(count);
        _dataList = new System.Collections.Generic.List<PlayerStates>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlayerStates _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PlayerStates.DeserializePlayerStates(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PlayerStates> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PlayerStates> DataList => _dataList;

    public PlayerStates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PlayerStates Get(int key) => _dataMap[key];
    public PlayerStates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

