
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPlayerStateData
{
    private readonly System.Collections.Generic.Dictionary<int, PlayerStateData> _dataMap;
    private readonly System.Collections.Generic.List<PlayerStateData> _dataList;
    
    public TbPlayerStateData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayerStateData>(count);
        _dataList = new System.Collections.Generic.List<PlayerStateData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PlayerStateData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PlayerStateData.DeserializePlayerStateData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, PlayerStateData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PlayerStateData> DataList => _dataList;

    public PlayerStateData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PlayerStateData Get(int key) => _dataMap[key];
    public PlayerStateData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

