
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbUnitData
{
    private readonly System.Collections.Generic.Dictionary<int, UnitData> _dataMap;
    private readonly System.Collections.Generic.List<UnitData> _dataList;
    
    public TbUnitData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, UnitData>(count);
        _dataList = new System.Collections.Generic.List<UnitData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UnitData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.UnitData.DeserializeUnitData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, UnitData> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UnitData> DataList => _dataList;

    public UnitData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UnitData Get(int key) => _dataMap[key];
    public UnitData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

