
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UnitAttData : Luban.BeanBase
{
    public UnitAttData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["atk"].IsNumber) { throw new SerializationException(); }  Atk = _buf["atk"]; }
        { if(!_buf["critical_hit_rate"].IsNumber) { throw new SerializationException(); }  CriticalHitRate = _buf["critical_hit_rate"]; }
        { if(!_buf["critical_hit_multiple"].IsNumber) { throw new SerializationException(); }  CriticalHitMultiple = _buf["critical_hit_multiple"]; }
    }

    public static UnitAttData DeserializeUnitAttData(JSONNode _buf)
    {
        return new UnitAttData(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Atk;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CriticalHitRate;
    /// <summary>
    /// 暴击伤害加成
    /// </summary>
    public readonly float CriticalHitMultiple;
   
    public const int __ID__ = -2071851097;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "atk:" + Atk + ","
        + "criticalHitRate:" + CriticalHitRate + ","
        + "criticalHitMultiple:" + CriticalHitMultiple + ","
        + "}";
    }
}
}

