
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UnitData : Luban.BeanBase
{
    public UnitData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["info"].IsString) { throw new SerializationException(); }  Info = _buf["info"]; }
        { if(!_buf["prefab_path"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefab_path"]; }
        { if(!_buf["att_id"].IsNumber) { throw new SerializationException(); }  AttId = _buf["att_id"]; }
    }

    public static UnitData DeserializeUnitData(JSONNode _buf)
    {
        return new UnitData(_buf);
    }

    /// <summary>
    /// 单位id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Info;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 属性表ID
    /// </summary>
    public readonly int AttId;
   
    public const int __ID__ = -228507794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "info:" + Info + ","
        + "prefabPath:" + PrefabPath + ","
        + "attId:" + AttId + ","
        + "}";
    }
}
}

